---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scanner-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-scanner
    aqua.component: scanner
{{ include "aqua.labels" . | indent 4 }}
data:
  SCALOCK_LOG_LEVEL: {{ .Values.logLevel | default "INFO" }}
  {{- if .Values.enableLivenessProbe }}
  AQUA_HEALTH_MONITOR_ENABLED: "true"
  AQUA_HEALTH_MONITOR_PORT: {{ .Values.livenessProbe.httpGet.port }}
  {{- end }}
  {{- if .Values.cyberCenter.mtls.enabled }}
  AQUA_PRIVATE_KEY: "/opt/aquasec/ssl/key.pem"
  AQUA_PUBLIC_KEY: "/opt/aquasec/ssl/cert.pem"
  AQUA_ROOT_CA: "/opt/aquasec/ssl/ca.pem"
  {{- if .Values.cyberCenter.mtls.rootCA_fileName }}
  OFFLINE_CC_MTLS_ENABLE: "1"
  {{- end }}
  {{- end }}