{{- $v := .Values.connect }}
{{- $name := printf "%s-%s" (include "chart.fullname" . ) "connector" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
{{- $v.service.annotations | toYaml | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ $v.service.port | default $v.port }}
    protocol: TCP
    targetPort: {{ $v.port }}
  type: {{ $v.service.type | default "ClusterIP" }}
